import tkinter as tk
from tkinter import ttk
#def calculadora():
#pass
def on_button7Click():
   textoActual=label3Text.get()
   label3Text.set(textoActual+"1")
pass

win=tk.Tk()
win.title("Calculadora")
win.resizable(0,0)
Label1=ttk.Label(win,text="Bienvenido, ingrese a continuación los valores y la operación que desea realizar.")
Label1.grid(row=0,column=0)
Label2=ttk.Label(win,text="Dato 1")
Label2.grid(row=1,column=0)
Valor1=tk.StringVar()
Label3=ttk.Label(win,text="")
label3Text=tk.StringVar()
Label3.configure(textvar=label3Text)
Label3.grid(row=1,column=1)
Label6=ttk.Label(win,text="Dato 2")
Label6.grid(row=2,column=0)
Valor2=tk.StringVar()
txtEntry=ttk.Entry(win,textvariable=Valor2)
txtEntry.grid(row=2,column=1)
boton1=ttk.Button(win,text="7")
boton1.grid(row=3,column=2)
boton2=ttk.Button(win,text="8")
boton2.grid(row=3,column=3)
boton3=ttk.Button(win,text="9")
boton3.grid(row=3,column=4)
boton4=ttk.Button(win,text="4")
boton4.grid(row=4,column=2)
boton5=ttk.Button(win,text="5")
boton5.grid(row=4,column=3)
boton6=ttk.Button(win,text="6")
boton6.grid(row=4,column=4)
boton7=ttk.Button(win,text="1",command=on_button7Click)
boton7.grid(row=5,column=2)
boton8=ttk.Button(win,text="2")
boton8.grid(row=5,column=3)
boton9=ttk.Button(win,text="3")
boton9.grid(row=5,column=4)
boton10=ttk.Button(win,text="0")
boton10.grid(row=6,column=3)
boton11=ttk.Button(win,text=".")
boton11.grid(row=6,column=4)
Label4=ttk.Label(win,text="Resultado")
Label4.grid(row=7,column=0)
Res=tk.StringVar()
Label5=ttk.Label(win,text="")
label5Text=tk.StringVar()
Label5.configure(textvar=label5Text)
Label5.grid(row=7,column=1)


win.mainloop()

